name: GraalVM for JDK 19
on:
  release:
    types: [published]
jobs:
  build:
    name: awt-test on ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            arch: linux-amd64
    steps:
      - name: 拉取项目
        uses: actions/checkout@v3

      - name: 配置环境
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.RELEASE_TOKEN }}
          native-image-job-reports: 'true'
          cache: maven

      - name: 构建 Native Image
        run: |
          cd /home/runner/work/awt-test/awt-test
          mvn native:compile -Pnative -Dmaven.test.skip=true

      - name: 打包
        run: |
          cd /home/runner/work/awt-test/awt-test/target
          tar -zcvf awt-test.tar.gz awt-test

      - name: 上传 Native Image
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: awt-test-graalvm-jdk19.tar.gz
          asset_path: /home/runner/work/awt-test/awt-test/target/*.tar.gz
          asset_content_type: application/x-compressed-tar